

services:
  web:
    build: .
    container_name: mes-parafina-app-compose
    restart: always
    command: gunicorn --worker-class eventlet -w 4 --bind 0.0.0.0:5000 --preload "run:app" --max-requests 1000 --max-requests-jitter 50
    ports:
      - "8080:5000" # Aplikacja webowa powinna być dostępna na porcie 8080
    volumes:
      - .:/app
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - MYSQLUSER=${MYSQLUSER}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQLHOST=db # Hostem jest nazwa usługi bazy danych
      - TZ=UTC
      - FLASK_ENV=production
    networks:
      - mes-parafina-net
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: mes-parafina-mysql-db-compose
    restart: always
    # === DODANA SEKCJA ===
    ports:
      # Mapuj port 3306 na hoście (Twój komputer) do portu 3306 w kontenerze
      - "3306:3306"
    # ===================
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=mes_parafina_db
      - MYSQL_USER=${MYSQLUSER}
      # Uwaga: obraz MySQL używa MYSQL_PASSWORD do ustawienia hasła dla nowo tworzonego użytkownika
      - MYSQL_PASSWORD=${MYSQL_PASSWORD_FOR_USER}
      - TZ=UTC
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - mes-parafina-net

  redis:
    image: "redis:alpine"
    container_name: mes-parafina-redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - mes-parafina-net

  celery-worker:
    build: .
    restart: always
    command: ["celery", "-A", "celery_app.celery", "worker", "-B", "-E", "-l", "info", "--scheduler", "celery_sqlalchemy_scheduler.schedulers.DatabaseScheduler", "--concurrency=2"]
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - MYSQLUSER=${MYSQLUSER}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQLHOST=db
      - REDIS_URL=redis://redis:6379/0
      - SENSORS_INTERVAL=${SENSORS_INTERVAL:-10.0}
      - ALARMS_INTERVAL=${ALARMS_INTERVAL:-5.0}
      - SENSORS_ENABLED=${SENSORS_ENABLED:-true}
      - ALARMS_ENABLED=${ALARMS_ENABLED:-true}
    networks:
      - mes-parafina-net
    volumes:
      - .:/app
    depends_on:
      - web
      - redis

  flower:
    build: .
    restart: always
    command: ["celery", "-A", "celery_app.celery", "flower", "--port=5555", "--broker=redis://redis:6379/0", "--persistent=true"]
    ports:
      - "5555:5555"
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - MYSQLUSER=${MYSQLUSER}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQLHOST=db
      - REDIS_URL=redis://redis:6379/0
      - FLOWER_UNAUTHENTICATED_API=true
    networks:
      - mes-parafina-net
    depends_on:
      - redis

# Definicja sieci
networks:
  mes-parafina-net:
    driver: bridge

# Definicja wolumenu
volumes:
  mysql_data:
    driver: local