"""Dodaj quantity_in_mix do MixComponents

Revision ID: 06dde16cfa2b
Revises: c548ab442b1c
Create Date: 2025-08-10 00:45:33.403902

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06dde16cfa2b'
down_revision: Union[str, None] = 'c548ab442b1c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
