"""Historia_podgrzewania

Revision ID: 090938ad26c1
Revises: 8a147ed88e79
Create Date: 2025-10-11 03:06:06.034004

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '090938ad26c1'
down_revision: Union[str, None] = '8a147ed88e79'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('historia_podgrzewania',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_sprzetu', sa.Integer(), nullable=False),
    sa.Column('id_mieszaniny', sa.Integer(), nullable=False),
    sa.Column('czas_startu', sa.DateTime(), nullable=False),
    sa.Column('temp_startowa', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('czas_konca', sa.DateTime(), nullable=True),
    sa.Column('temp_koncowa', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('temperatura_zewnetrzna', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('waga_wsadu', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['id_mieszaniny'], ['tank_mixes.id'], ),
    sa.ForeignKeyConstraint(['id_sprzetu'], ['sprzet.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_historia_podgrzewania_id_mieszaniny'), 'historia_podgrzewania', ['id_mieszaniny'], unique=False)
    op.create_index(op.f('ix_historia_podgrzewania_id_sprzetu'), 'historia_podgrzewania', ['id_sprzetu'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_historia_podgrzewania_id_sprzetu'), table_name='historia_podgrzewania')
    op.drop_index(op.f('ix_historia_podgrzewania_id_mieszaniny'), table_name='historia_podgrzewania')
    op.drop_table('historia_podgrzewania')
    # ### end Alembic commands ###
