"""Dodaj uwagi serwisowe do sprzetu

Revision ID: 1bda91719c21
Revises: 
Create Date: 2025-08-08 07:11:03.649812

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1bda91719c21'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sprzet', sa.Column('uwagi_serwisowe', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sprzet', 'uwagi_serwisowe')
    # ### end Alembic commands ###
