"""Ipomiar.pl - dodanie device_id etc

Revision ID: 39f7fd1d9899
Revises: 960722151c01
Create Date: 2025-12-06 12:33:52.933585

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '39f7fd1d9899'
down_revision: Union[str, None] = '960722151c01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sprzet', sa.Column('ipomiar_device_id', sa.String(length=50), nullable=True, comment='ID urządzenia w systemie iPomiar.pl do odczytu poziomu'))
    op.add_column('sprzet', sa.Column('poziom_pusty_mm', sa.DECIMAL(precision=10, scale=2), nullable=True, comment='Odczyt czujnika w mm, gdy zbiornik jest pusty'))
    op.add_column('sprzet', sa.Column('poziom_pelny_mm', sa.DECIMAL(precision=10, scale=2), nullable=True, comment='Odczyt czujnika w mm, gdy zbiornik jest pełny'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sprzet', 'poziom_pelny_mm')
    op.drop_column('sprzet', 'poziom_pusty_mm')
    op.drop_column('sprzet', 'ipomiar_device_id')
    # ### end Alembic commands ###
