"""uwagi kolektora apollo sesje remove

Revision ID: 43481390357c
Revises: bfb1f6a125eb
Create Date: 2025-09-02 21:21:04.494663

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '43481390357c'
down_revision: Union[str, None] = 'bfb1f6a125eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('apollo_sesje', 'uwagi_do_kolektora')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('apollo_sesje', sa.Column('uwagi_do_kolektora', mysql.TEXT(charset='utf8mb4', collation='utf8mb4_unicode_ci'), nullable=True))
    # ### end Alembic commands ###
