"""Rozbudowa modeli Sprzet i TankMixes o statusy procesowe

Revision ID: 4734460e7c5c
Revises: 4d5d8ed9c6d0
Create Date: 2025-08-25 16:32:42.640075

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4734460e7c5c'
down_revision: Union[str, None] = '4d5d8ed9c6d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
