"""Add earth_pallets table for tracking used bleaching earth

Revision ID: 4ca33c18694f
Revises: c6adf1074259
Create Date: 2025-10-05 23:34:35.436947

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ca33c18694f'
down_revision: Union[str, None] = 'c6adf1074259'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('earth_pallets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lp', sa.VARCHAR(length=10), nullable=False, comment='Numer palety, np. B1, B99, C1'),
    sa.Column('waga', sa.DECIMAL(precision=10, scale=2), nullable=False, comment='Waga w kilogramach'),
    sa.Column('zwazyl', sa.VARCHAR(length=100), nullable=True, comment='Nazwisko osoby ważącej'),
    sa.Column('data_wazenia', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Data i czas ważenia'),
    sa.Column('uwagi', sa.Text(), nullable=True, comment='Dodatkowe uwagi'),
    sa.PrimaryKeyConstraint('id'),
    comment='Palety ze zużytą ziemią filtracyjną'
    )
    op.create_index('lp_unique', 'earth_pallets', ['lp'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('lp_unique', table_name='earth_pallets')
    op.drop_table('earth_pallets')
    # ### end Alembic commands ###
