"""Przerwanie cyklu zaleznosci sprzet-tank_mixes

Revision ID: 4d5d8ed9c6d0
Revises: 542d9616f8cc
Create Date: 2025-08-12 13:13:39.732634

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d5d8ed9c6d0'
down_revision: Union[str, None] = '542d9616f8cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('sprzet_ibfk_1', 'sprzet', type_='foreignkey')
    op.drop_index('active_mix_id', table_name='sprzet')
    op.create_index(op.f('ix_sprzet_active_mix_id'), 'sprzet', ['active_mix_id'], unique=False)
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('sprzet_ibfk_1', 'sprzet', 'tank_mixes', ['active_mix_id'], ['id'])
    op.drop_index(op.f('ix_sprzet_active_mix_id'), table_name='sprzet')
    op.create_index('active_mix_id', 'sprzet', ['active_mix_id'], unique=True)
    # ### end Alembic commands ###
