"""Dodaj quantity_in_mix do MixComponents

Revision ID: 54e33019e87e
Revises: 06dde16cfa2b
Create Date: 2025-08-10 01:11:49.578535

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '54e33019e87e'
down_revision: Union[str, None] = '06dde16cfa2b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
