"""Dodanie Batches

Revision ID: 688a598dfd29
Revises: f4d152533730
Create Date: 2025-08-09 20:28:49.692613

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '688a598dfd29'
down_revision: Union[str, None] = 'f4d152533730'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('batches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('unique_code', sa.String(length=50), nullable=False),
    sa.Column('material_type', sa.String(length=50), nullable=False),
    sa.Column('source_type', mysql.ENUM('CYS', 'APOLLO'), nullable=False),
    sa.Column('source_name', sa.String(length=50), nullable=False),
    sa.Column('initial_quantity', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('current_quantity', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('creation_date', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('status', mysql.ENUM('ACTIVE', 'DEPLETED', 'ARCHIVED'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('unique_code')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('batches')
    # ### end Alembic commands ###
