"""Dodaj quantity_in_mix do MixComponents

Revision ID: 7911d02d23f3
Revises: 54e33019e87e
Create Date: 2025-08-10 01:14:28.385222

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7911d02d23f3'
down_revision: Union[str, None] = '54e33019e87e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mix_components', sa.Column('quantity_in_mix', sa.DECIMAL(precision=10, scale=2), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mix_components', 'quantity_in_mix')
    # ### end Alembic commands ###
