"""Partie_apollo

Revision ID: 8335df2962f7
Revises: a26a6da325e7
Create Date: 2025-10-17 00:35:16.977459

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '8335df2962f7'
down_revision: Union[str, None] = 'a26a6da325e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('partie_apollo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_sprzetu', sa.Integer(), nullable=True),
    sa.Column('unikalny_kod', sa.VARCHAR(length=50), nullable=False),
    sa.Column('nazwa_partii', sa.VARCHAR(length=100), nullable=False),
    sa.Column('typ_surowca', sa.VARCHAR(length=50), nullable=False),
    sa.Column('waga_poczatkowa_kg', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('waga_aktualna_kg', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('data_utworzenia', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('status_partii', mysql.ENUM('Wytapiany', 'Archiwalna'), nullable=False),
    sa.ForeignKeyConstraint(['id_sprzetu'], ['sprzet.id'], name='partie_apollo_ibfk_1', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('unikalny_kod')
    )
    op.create_index('id_sprzetu', 'partie_apollo', ['id_sprzetu'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('id_sprzetu', table_name='partie_apollo')
    op.drop_table('partie_apollo')
    # ### end Alembic commands ###
