"""Add foreign key from OperacjeLog to TankMixes

Revision ID: 8a147ed88e79
Revises: 4ca33c18694f
Create Date: 2025-10-10 23:28:57.726290

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a147ed88e79'
down_revision: Union[str, None] = '4ca33c18694f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('operacje_log', sa.Column('id_tank_mix', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_operacje_log_id_tank_mix'), 'operacje_log', ['id_tank_mix'], unique=False)
    op.create_foreign_key(None, 'operacje_log', 'tank_mixes', ['id_tank_mix'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'operacje_log', type_='foreignkey')
    op.drop_index(op.f('ix_operacje_log_id_tank_mix'), table_name='operacje_log')
    op.drop_column('operacje_log', 'id_tank_mix')
    # ### end Alembic commands ###
