"""Partie_apollo_3

Revision ID: 96736366f070
Revises: e3748dad40b6
Create Date: 2025-10-17 05:06:32.477703

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '96736366f070'
down_revision: Union[str, None] = 'e3748dad40b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('partie_apollo', sa.Column('typ_transformacji', mysql.ENUM('NOWA', 'TRANSFER', 'KOREKTA', 'ZAKONCZENIE'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('partie_apollo', 'typ_transformacji')
    # ### end Alembic commands ###
