"""czyszczenie_po_prototypie_2

Revision ID: a26a6da325e7
Revises: c32918679fd0
Create Date: 2025-10-17 00:00:45.972798

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'a26a6da325e7'
down_revision: Union[str, None] = 'c32918679fd0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('probki_ocena')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('probki_ocena',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('id_partii', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id_cyklu_filtracyjnego', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('czas_pobrania', mysql.DATETIME(), nullable=False),
    sa.Column('czas_oceny', mysql.DATETIME(), nullable=True),
    sa.Column('wynik_oceny', mysql.ENUM('pozytywna', 'negatywna', 'oczekuje'), server_default=sa.text("'oczekuje'"), nullable=True),
    sa.Column('ocena_koloru', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=50), nullable=True),
    sa.Column('decyzja', mysql.ENUM('kontynuuj_filtracje', 'wyslij_do_magazynu', 'dodaj_ziemie'), nullable=True),
    sa.Column('operator_oceniajacy', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=100), nullable=True),
    sa.Column('uwagi', mysql.TEXT(charset='utf8mb4', collation='utf8mb4_0900_ai_ci'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    comment='Rejestr próbek i ich ocen podczas procesu filtracji',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_comment='Rejestr próbek i ich ocen podczas procesu filtracji',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
