"""uwagi kolektora apollo sesje

Revision ID: bfb1f6a125eb
Revises: eb440ad558c6
Create Date: 2025-09-02 21:17:42.300920

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bfb1f6a125eb'
down_revision: Union[str, None] = 'eb440ad558c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('apollo_sesje', sa.Column('uwagi_do_kolektora', sa.Text(collation='utf8mb4_unicode_ci'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('apollo_sesje', 'uwagi_do_kolektora')
    # ### end Alembic commands ###
