"""Kalibracja zbiornikow 1

Revision ID: c1de97e2d69a
Revises: c63b10fdc2a7
Create Date: 2026-02-19 09:51:41.733226

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c1de97e2d69a'
down_revision: Union[str, None] = 'c63b10fdc2a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tank_calibration_points',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_sprzetu', sa.Integer(), nullable=False),
    sa.Column('odczyt_mm', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('waga_tony', sa.DECIMAL(precision=10, scale=3), nullable=False),
    sa.Column('data_kalibracji', sa.DateTime(), nullable=True),
    sa.Column('uwagi', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['id_sprzetu'], ['sprzet.id'], name='tank_calibration_points_ibfk_1', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_sprzetu', 'odczyt_mm', name='uq_tank_calibration_sprzet_mm'),
    comment='Punkty kalibracyjne dla zbiorników - konwersja mm -> tony'
    )
    op.create_index('idx_tank_calibration_sprzet', 'tank_calibration_points', ['id_sprzetu'], unique=False)
    op.create_index('idx_tank_calibration_sprzet_mm', 'tank_calibration_points', ['id_sprzetu', 'odczyt_mm'], unique=False)
    op.create_index(op.f('ix_tank_calibration_points_id_sprzetu'), 'tank_calibration_points', ['id_sprzetu'], unique=False)
    op.add_column('sprzet', sa.Column('poziom_aktualny_tony', sa.DECIMAL(precision=10, scale=3), nullable=True, comment='Aktualna waga w tonach obliczona z kalibracji'))
    op.add_column('sprzet', sa.Column('pojemnosc_tony', sa.DECIMAL(precision=5, scale=1), nullable=True, comment='Maksymalna pojemność zbiornika w tonach (max 90T) dla ograniczenia zakresu kalibracji'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sprzet', 'pojemnosc_tony')
    op.drop_column('sprzet', 'poziom_aktualny_tony')
    op.drop_index(op.f('ix_tank_calibration_points_id_sprzetu'), table_name='tank_calibration_points')
    op.drop_index('idx_tank_calibration_sprzet_mm', table_name='tank_calibration_points')
    op.drop_index('idx_tank_calibration_sprzet', table_name='tank_calibration_points')
    op.drop_table('tank_calibration_points')
    # ### end Alembic commands ###
