"""czyszczenie_po_prototypie

Revision ID: c32918679fd0
Revises: cd0ae2394649
Create Date: 2025-10-16 22:52:16.034723

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'c32918679fd0'
down_revision: Union[str, None] = 'cd0ae2394649'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('operacje_log_ibfk_1', 'operacje_log', type_='foreignkey')
    op.drop_constraint('partie_historia_ibfk_2', 'partie_historia', type_='foreignkey')
    op.drop_constraint('partie_historia_ibfk_1', 'partie_historia', type_='foreignkey')
    op.drop_constraint('probki_ocena_ibfk_2', 'probki_ocena', type_='foreignkey')
    op.drop_constraint('probki_ocena_ibfk_1', 'probki_ocena', type_='foreignkey')
    op.drop_constraint('partie_powiazania_ibfk_3', 'partie_powiazania', type_='foreignkey')
    op.drop_constraint('partie_powiazania_ibfk_2', 'partie_powiazania', type_='foreignkey')
    op.drop_constraint('partie_powiazania_ibfk_1', 'partie_powiazania', type_='foreignkey')
    op.drop_constraint('fk_partia_skladowa', 'partie_skladniki', type_='foreignkey')
    op.drop_constraint('fk_partia_wynikowa', 'partie_skladniki', type_='foreignkey')
    op.drop_constraint('partie_probki_ibfk_1', 'partie_probki', type_='foreignkey')
    op.drop_constraint('partie_statusy_ibfk_1', 'partie_statusy', type_='foreignkey')
    op.drop_constraint('partie_statusy_ibfk_2', 'partie_statusy', type_='foreignkey')
    op.drop_constraint('cykle_filtracyjne_ibfk_1', 'cykle_filtracyjne', type_='foreignkey')
    op.drop_constraint('partie_surowca_ibfk_1', 'partie_surowca', type_='foreignkey')
    
    op.drop_index('idx_data_pobrania', table_name='partie_probki')
    op.drop_index('idx_numer_probki', table_name='partie_probki')
    op.drop_index('idx_partia', table_name='partie_probki')
    op.drop_index('idx_status', table_name='partie_probki')
    op.drop_index('numer_probki', table_name='partie_probki')
    
    op.drop_index('idx_partia_skladowa', table_name='partie_skladniki')
    op.drop_index('idx_partia_wynikowa', table_name='partie_skladniki')
    
    op.drop_index('idx_partia_docelowa', table_name='partie_powiazania')
    op.drop_index('idx_partia_zrodlowa', table_name='partie_powiazania')
    op.drop_index('idx_typ_powiazania', table_name='partie_powiazania')
    
    op.drop_index('idx_partia_czas', table_name='probki_ocena')
    
    op.drop_index('idx_filtr_czas', table_name='cykle_filtracyjne')
    op.drop_index('idx_partia_cykl', table_name='cykle_filtracyjne')
    op.drop_index('idx_data_operacji', table_name='partie_historia')
    op.drop_index('idx_partia', table_name='partie_historia')
    op.drop_index('idx_typ_operacji', table_name='partie_historia')
    op.drop_index('nazwa_statusu', table_name='statusy')
    
    
    op.drop_index('nazwa_statusu', table_name='statusy_partii')
    
    
    op.drop_index('idx_etap_procesu', table_name='partie_surowca')
    op.drop_index('idx_typ_transformacji', table_name='partie_surowca')
    op.drop_index('nazwa_partii', table_name='partie_surowca')
    op.drop_index('unikalny_kod', table_name='partie_surowca')


    
    

    op.drop_table('partie_statusy')

    op.drop_table('partie_probki')

    op.drop_table('partie_powiazania')

    op.drop_table('partie_skladniki')

    op.drop_table('partie_surowca')
    op.drop_table('partie_historia')
    op.drop_table('cykle_filtracyjne')
    
    op.drop_table('statusy')
    op.drop_table('statusy_partii')
    
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('operacje_log_ibfk_1', 'operacje_log', 'partie_surowca', ['id_partii_surowca'], ['id'], ondelete='SET NULL')
    op.create_table('partie_surowca',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('unikalny_kod', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=50), nullable=False, comment='Identyfikator partii, np. T10-20231027-1430-APOLLO'),
    sa.Column('typ_surowca', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=50), nullable=True),
    sa.Column('zrodlo_pochodzenia', mysql.ENUM('apollo', 'cysterna'), nullable=False),
    sa.Column('waga_poczatkowa_kg', mysql.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('waga_aktualna_kg', mysql.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('data_utworzenia', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('id_sprzetu', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('nazwa_partii', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=100), nullable=False),
    sa.Column('rodzaj_surowca', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=50), nullable=True),
    sa.Column('id_aktualnego_sprzetu', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('status_partii', mysql.ENUM('W magazynie brudnym', 'Surowy w reaktorze', 'Budowanie placka', 'Przelewanie', 'Filtrowanie', 'Oczekiwanie na ocenę', 'Do ponownej filtracji', 'Dobielanie', 'Gotowy do wysłania', 'W magazynie czystym', 'Archiwalna'), nullable=False),
    sa.Column('aktualny_etap_procesu', mysql.ENUM('surowy', 'placek', 'przelew', 'w_kole', 'ocena_probki', 'dmuchanie', 'gotowy', 'wydmuch'), server_default=sa.text("'surowy'"), nullable=True),
    sa.Column('numer_cyklu_aktualnego', mysql.INTEGER(), server_default=sa.text("'0'"), autoincrement=False, nullable=True),
    sa.Column('czas_rozpoczecia_etapu', mysql.DATETIME(), nullable=True),
    sa.Column('planowany_czas_zakonczenia', mysql.DATETIME(), nullable=True),
    sa.Column('id_aktualnego_filtra', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=10), nullable=True),
    sa.Column('reaktor_docelowy', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=10), nullable=True),
    sa.Column('ilosc_cykli_filtracyjnych', mysql.INTEGER(), server_default=sa.text("'0'"), autoincrement=False, nullable=True),
    sa.Column('historia_operacji', mysql.JSON(), nullable=True),
    sa.Column('typ_transformacji', mysql.ENUM('NOWA', 'TRANSFER', 'FILTRACJA', 'MIESZANIE', 'DZIELENIE'), server_default=sa.text("'NOWA'"), nullable=True),
    sa.Column('etap_procesu', mysql.ENUM('SUROWA', 'W_PROCESIE', 'FILTROWANA', 'GOTOWA', 'ZATWIERDZONA', 'ODRZUCONA'), server_default=sa.text("'SUROWA'"), nullable=True),
    sa.Column('pochodzenie_opis', mysql.TEXT(charset='utf8mb4', collation='utf8mb4_0900_ai_ci'), nullable=True),
    sa.Column('data_ostatniej_modyfikacji', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('utworzona_przez', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=100), nullable=True),
    sa.Column('certyfikat_jakosci', mysql.TEXT(charset='utf8mb4', collation='utf8mb4_0900_ai_ci'), nullable=True),
    sa.Column('uwagi_operatora', mysql.TEXT(charset='utf8mb4', collation='utf8mb4_0900_ai_ci'), nullable=True),
    sa.ForeignKeyConstraint(['id_sprzetu'], ['sprzet.id'], name='partie_surowca_ibfk_1', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    comment='Każdy wiersz to unikalna partia produkcyjna surowca',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_comment='Każdy wiersz to unikalna partia produkcyjna surowca',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('unikalny_kod', 'partie_surowca', ['unikalny_kod'], unique=True)
    op.create_index('nazwa_partii', 'partie_surowca', ['nazwa_partii'], unique=True)
    op.create_index('idx_typ_transformacji', 'partie_surowca', ['typ_transformacji'], unique=False)
    op.create_index('idx_etap_procesu', 'partie_surowca', ['etap_procesu'], unique=False)
    op.create_table('statusy_partii',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nazwa_statusu', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('opis', mysql.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('nazwa_statusu', 'statusy_partii', ['nazwa_statusu'], unique=True)
    op.create_table('statusy',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nazwa_statusu', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=50), nullable=False, comment='Np. Surowy, Filtrowany, Dobielony, Wydmuch'),
    sa.PrimaryKeyConstraint('id'),
    comment='Słownik możliwych statusów partii surowca',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_comment='Słownik możliwych statusów partii surowca',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('nazwa_statusu', 'statusy', ['nazwa_statusu'], unique=True)
    op.create_table('partie_historia',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('id_partii_surowca', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('typ_operacji', mysql.ENUM('UTWORZENIE', 'TRANSFER', 'FILTRACJA', 'MIESZANIE', 'DZIELENIE', 'ZMIANA_STANU', 'POBOR_PROBKI', 'ZATWIERDZENIE'), nullable=False),
    sa.Column('data_operacji', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('operator', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=100), nullable=True),
    sa.Column('lokalizacja_przed', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=100), nullable=True),
    sa.Column('lokalizacja_po', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=100), nullable=True),
    sa.Column('waga_przed', mysql.DECIMAL(precision=10, scale=3), nullable=True),
    sa.Column('waga_po', mysql.DECIMAL(precision=10, scale=3), nullable=True),
    sa.Column('parametry_operacji', mysql.JSON(), nullable=True),
    sa.Column('opis_operacji', mysql.TEXT(charset='utf8mb4', collation='utf8mb4_0900_ai_ci'), nullable=True),
    sa.Column('id_operacji_log', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['id_operacji_log'], ['operacje_log.id'], name='partie_historia_ibfk_2', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['id_partii_surowca'], ['partie_surowca.id'], name='partie_historia_ibfk_1', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('idx_typ_operacji', 'partie_historia', ['typ_operacji'], unique=False)
    op.create_index('idx_partia', 'partie_historia', ['id_partii_surowca'], unique=False)
    op.create_index('idx_data_operacji', 'partie_historia', ['data_operacji'], unique=False)
    op.create_table('cykle_filtracyjne',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('id_partii', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('numer_cyklu', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('typ_cyklu', mysql.ENUM('placek', 'filtracja', 'dmuchanie'), nullable=True),
    sa.Column('id_filtra', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=10), nullable=True),
    sa.Column('reaktor_startowy', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=10), nullable=True),
    sa.Column('reaktor_docelowy', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=10), nullable=True),
    sa.Column('czas_rozpoczecia', mysql.DATETIME(), nullable=True),
    sa.Column('czas_zakonczenia', mysql.DATETIME(), nullable=True),
    sa.Column('czas_trwania_minut', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('wynik_oceny', mysql.ENUM('pozytywna', 'negatywna', 'oczekuje'), nullable=True),
    sa.Column('komentarz', mysql.TEXT(charset='utf8mb4', collation='utf8mb4_0900_ai_ci'), nullable=True),
    sa.ForeignKeyConstraint(['id_partii'], ['partie_surowca.id'], name='cykle_filtracyjne_ibfk_1', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    comment='Historia wszystkich cykli filtracyjnych dla każdej partii',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_comment='Historia wszystkich cykli filtracyjnych dla każdej partii',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('idx_partia_cykl', 'cykle_filtracyjne', ['id_partii', 'numer_cyklu'], unique=False)
    op.create_index('idx_filtr_czas', 'cykle_filtracyjne', ['id_filtra', 'czas_rozpoczecia'], unique=False)
    op.create_table('probki_ocena',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('id_partii', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id_cyklu_filtracyjnego', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('czas_pobrania', mysql.DATETIME(), nullable=False),
    sa.Column('czas_oceny', mysql.DATETIME(), nullable=True),
    sa.Column('wynik_oceny', mysql.ENUM('pozytywna', 'negatywna', 'oczekuje'), server_default=sa.text("'oczekuje'"), nullable=True),
    sa.Column('ocena_koloru', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=50), nullable=True),
    sa.Column('decyzja', mysql.ENUM('kontynuuj_filtracje', 'wyslij_do_magazynu', 'dodaj_ziemie'), nullable=True),
    sa.Column('operator_oceniajacy', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=100), nullable=True),
    sa.Column('uwagi', mysql.TEXT(charset='utf8mb4', collation='utf8mb4_0900_ai_ci'), nullable=True),
    sa.ForeignKeyConstraint(['id_cyklu_filtracyjnego'], ['cykle_filtracyjne.id'], name='probki_ocena_ibfk_2', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_partii'], ['partie_surowca.id'], name='probki_ocena_ibfk_1', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    comment='Rejestr próbek i ich ocen podczas procesu filtracji',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_comment='Rejestr próbek i ich ocen podczas procesu filtracji',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('idx_partia_czas', 'probki_ocena', ['id_partii', 'czas_pobrania'], unique=False)
    op.create_table('partie_powiazania',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('partia_zrodlowa_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('partia_docelowa_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('typ_powiazania', mysql.ENUM('DZIELENIE', 'LACZENIE', 'TRANSFORMACJA'), nullable=False),
    sa.Column('procent_udzialu', mysql.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('data_powiazania', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('id_operacji_log', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('uwagi', mysql.TEXT(charset='utf8mb4', collation='utf8mb4_0900_ai_ci'), nullable=True),
    sa.ForeignKeyConstraint(['id_operacji_log'], ['operacje_log.id'], name='partie_powiazania_ibfk_3', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['partia_docelowa_id'], ['partie_surowca.id'], name='partie_powiazania_ibfk_2', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['partia_zrodlowa_id'], ['partie_surowca.id'], name='partie_powiazania_ibfk_1', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('idx_typ_powiazania', 'partie_powiazania', ['typ_powiazania'], unique=False)
    op.create_index('idx_partia_zrodlowa', 'partie_powiazania', ['partia_zrodlowa_id'], unique=False)
    op.create_index('idx_partia_docelowa', 'partie_powiazania', ['partia_docelowa_id'], unique=False)
    op.create_table('partie_skladniki',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('id_partii_wynikowej', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id_partii_skladowej', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('waga_skladowa_kg', mysql.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('data_dodania', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['id_partii_skladowej'], ['partie_surowca.id'], name='fk_partia_skladowa', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['id_partii_wynikowej'], ['partie_surowca.id'], name='fk_partia_wynikowa', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    comment='Tabela łącząca partie-mieszaniny z ich składnikami.',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_comment='Tabela łącząca partie-mieszaniny z ich składnikami.',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('idx_partia_wynikowa', 'partie_skladniki', ['id_partii_wynikowej'], unique=False)
    op.create_index('idx_partia_skladowa', 'partie_skladniki', ['id_partii_skladowej'], unique=False)
    op.create_table('partie_probki',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('id_partii_surowca', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('numer_probki', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=50), nullable=False),
    sa.Column('data_pobrania', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('pobrana_przez', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=100), nullable=True),
    sa.Column('lokalizacja_pobrania', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=100), nullable=True),
    sa.Column('typ_probki', mysql.ENUM('RUTYNOWA', 'KONTROLNA', 'REKLAMACYJNA', 'WALIDACYJNA'), server_default=sa.text("'RUTYNOWA'"), nullable=True),
    sa.Column('status_probki', mysql.ENUM('POBRANA', 'W_ANALIZIE', 'ZATWIERDZONA', 'ODRZUCONA'), server_default=sa.text("'POBRANA'"), nullable=True),
    sa.Column('wyniki_analizy', mysql.JSON(), nullable=True),
    sa.Column('data_analizy', mysql.TIMESTAMP(), nullable=True),
    sa.Column('analizowana_przez', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=100), nullable=True),
    sa.Column('uwagi', mysql.TEXT(charset='utf8mb4', collation='utf8mb4_0900_ai_ci'), nullable=True),
    sa.ForeignKeyConstraint(['id_partii_surowca'], ['partie_surowca.id'], name='partie_probki_ibfk_1', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('numer_probki', 'partie_probki', ['numer_probki'], unique=True)
    op.create_index('idx_status', 'partie_probki', ['status_probki'], unique=False)
    op.create_index('idx_partia', 'partie_probki', ['id_partii_surowca'], unique=False)
    op.create_index('idx_numer_probki', 'partie_probki', ['numer_probki'], unique=False)
    op.create_index('idx_data_pobrania', 'partie_probki', ['data_pobrania'], unique=False)
    op.create_table('partie_statusy',
    sa.Column('id_partii', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id_statusu', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('data_nadania', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['id_partii'], ['partie_surowca.id'], name='partie_statusy_ibfk_1', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_statusu'], ['statusy.id'], name='partie_statusy_ibfk_2', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_partii', 'id_statusu'),
    comment='Przypisuje wiele statusów do jednej partii',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_comment='Przypisuje wiele statusów do jednej partii',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
