"""Historia pomiarow - poziom z ipomiar.pl

Revision ID: c63b10fdc2a7
Revises: 39f7fd1d9899
Create Date: 2025-12-06 18:17:33.909998

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c63b10fdc2a7'
down_revision: Union[str, None] = '39f7fd1d9899'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('historia_pomiarow', sa.Column('poziom_mm', sa.DECIMAL(precision=10, scale=2), nullable=True, comment='Odczyt z czujnika ultradźwiękowego w mm'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('historia_pomiarow', 'poziom_mm')
    # ### end Alembic commands ###
