"""Dodanie tabeli AuditTrail do sledzenia zmian

Revision ID: cb7219e283a0
Revises: 7911d02d23f3
Create Date: 2025-08-10 20:53:30.380082

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb7219e283a0'
down_revision: Union[str, None] = '7911d02d23f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_trail',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('user_id', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False, comment='Np. Batches, TankMixes'),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('field_name', sa.String(length=50), nullable=True),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('operation_type', sa.String(length=50), nullable=False, comment='Np. CREATE, UPDATE, DELETE, CORRECTION'),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('audit_trail')
    # ### end Alembic commands ###
