"""OperacjeLog ilosc_workow

Revision ID: cd0ae2394649
Revises: 090938ad26c1
Create Date: 2025-10-12 05:34:54.327175

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd0ae2394649'
down_revision: Union[str, None] = '090938ad26c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('operacje_log', sa.Column('ilosc_workow', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('operacje_log', 'ilosc_workow')
    # ### end Alembic commands ###
