"""Usuniecie active_mix_id ze sprzetu w celu synchronizacji z kodem

Revision ID: d4c4e6b121e0
Revises: 
Create Date: 2025-08-11 01:30:36.008033

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'd4c4e6b121e0'
down_revision: Union[str, None] = '55c02b31917b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('active_mix_id', table_name='sprzet')
    op.drop_constraint('sprzet_ibfk_1', 'sprzet', type_='foreignkey')
    op.drop_column('sprzet', 'active_mix_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sprzet', sa.Column('active_mix_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('sprzet_ibfk_1', 'sprzet', 'tank_mixes', ['active_mix_id'], ['id'])
    op.create_index('active_mix_id', 'sprzet', ['active_mix_id'], unique=True)
    # ### end Alembic commands ###
