"""Partie_apollo_2

Revision ID: e3748dad40b6
Revises: 8335df2962f7
Create Date: 2025-10-17 00:51:58.298641

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'e3748dad40b6'
down_revision: Union[str, None] = '8335df2962f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('partie_apollo', sa.Column('zrodlo_pochodzenia', mysql.ENUM('apollo', 'cysterna'), nullable=False))
    op.alter_column('partie_apollo', 'id_sprzetu',
               existing_type=mysql.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('partie_apollo', 'id_sprzetu',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.drop_column('partie_apollo', 'zrodlo_pochodzenia')
    # ### end Alembic commands ###
