"""Zwiekszenie precyzji kolumn temperatury do DECIMAL(10, 6)

Revision ID: eb440ad558c6
Revises: f6bab5890f1d
Create Date: 2025-08-30 21:04:18.692844

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'eb440ad558c6'
down_revision: Union[str, None] = 'f6bab5890f1d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('historia_pomiarow', 'temperatura',
               existing_type=mysql.DECIMAL(precision=5, scale=2),
               type_=sa.DECIMAL(precision=10, scale=6),
               existing_nullable=True)
    op.alter_column('operator_temperatures', 'temperatura',
               existing_type=mysql.DECIMAL(precision=5, scale=2),
               type_=sa.DECIMAL(precision=10, scale=6),
               existing_nullable=False)
    op.alter_column('sprzet', 'temperatura_aktualna',
               existing_type=mysql.DECIMAL(precision=5, scale=2),
               type_=sa.DECIMAL(precision=10, scale=6),
               existing_nullable=True)
    op.alter_column('sprzet', 'temperatura_max',
               existing_type=mysql.DECIMAL(precision=5, scale=2),
               type_=sa.DECIMAL(precision=10, scale=6),
               existing_nullable=True,
               existing_server_default=sa.text("'120.00'"))
    op.alter_column('sprzet', 'temperatura_docelowa',
               existing_type=mysql.DECIMAL(precision=5, scale=2),
               type_=sa.DECIMAL(precision=10, scale=6),
               existing_comment='Temperatura zadana przez operatora',
               existing_nullable=True)
    op.alter_column('sprzet', 'szybkosc_grzania_c_na_minute',
               existing_type=mysql.DECIMAL(precision=5, scale=2),
               type_=sa.DECIMAL(precision=10, scale=6),
               existing_comment='Szacowana szybkość grzania w °C/min',
               existing_nullable=True)
    op.alter_column('sprzet', 'szybkosc_chlodzenia_c_na_minute',
               existing_type=mysql.DECIMAL(precision=5, scale=2),
               type_=sa.DECIMAL(precision=10, scale=6),
               existing_comment='Szacowana szybkość chłodzenia w °C/min',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sprzet', 'szybkosc_chlodzenia_c_na_minute',
               existing_type=sa.DECIMAL(precision=10, scale=6),
               type_=mysql.DECIMAL(precision=5, scale=2),
               existing_comment='Szacowana szybkość chłodzenia w °C/min',
               existing_nullable=True)
    op.alter_column('sprzet', 'szybkosc_grzania_c_na_minute',
               existing_type=sa.DECIMAL(precision=10, scale=6),
               type_=mysql.DECIMAL(precision=5, scale=2),
               existing_comment='Szacowana szybkość grzania w °C/min',
               existing_nullable=True)
    op.alter_column('sprzet', 'temperatura_docelowa',
               existing_type=sa.DECIMAL(precision=10, scale=6),
               type_=mysql.DECIMAL(precision=5, scale=2),
               existing_comment='Temperatura zadana przez operatora',
               existing_nullable=True)
    op.alter_column('sprzet', 'temperatura_max',
               existing_type=sa.DECIMAL(precision=10, scale=6),
               type_=mysql.DECIMAL(precision=5, scale=2),
               existing_nullable=True,
               existing_server_default=sa.text("'120.00'"))
    op.alter_column('sprzet', 'temperatura_aktualna',
               existing_type=sa.DECIMAL(precision=10, scale=6),
               type_=mysql.DECIMAL(precision=5, scale=2),
               existing_nullable=True)
    op.alter_column('operator_temperatures', 'temperatura',
               existing_type=sa.DECIMAL(precision=10, scale=6),
               type_=mysql.DECIMAL(precision=5, scale=2),
               existing_nullable=False)
    op.alter_column('historia_pomiarow', 'temperatura',
               existing_type=sa.DECIMAL(precision=10, scale=6),
               type_=mysql.DECIMAL(precision=5, scale=2),
               existing_nullable=True)
    # ### end Alembic commands ###
