"""test2

Revision ID: eea38fd5a104
Revises: 295b00ad5fb2
Create Date: 2025-08-08 13:42:16.355013

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eea38fd5a104'
down_revision: Union[str, None] = '295b00ad5fb2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sprzet', sa.Column('test2', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sprzet', 'test2')
    # ### end Alembic commands ###
