"""Rozbudowa modeli Sprzet i TankMixes o statusy procesowe

Revision ID: f6bab5890f1d
Revises: 4734460e7c5c
Create Date: 2025-08-25 16:36:26.809900

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'f6bab5890f1d'
down_revision: Union[str, None] = '4734460e7c5c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sprzet', sa.Column('szybkosc_grzania_c_na_minute', sa.DECIMAL(precision=5, scale=2), nullable=True, comment='Szacowana szybkość grzania w °C/min'))
    op.add_column('sprzet', sa.Column('szybkosc_chlodzenia_c_na_minute', sa.DECIMAL(precision=5, scale=2), nullable=True, comment='Szacowana szybkość chłodzenia w °C/min'))
    op.add_column('sprzet', sa.Column('stan_palnika', mysql.ENUM('WLACZONY', 'WYLACZONY'), nullable=True, comment='Aktualny stan palnika reaktora'))
    op.add_column('sprzet', sa.Column('filter_cake_status', sa.String(length=50), nullable=True, comment='Status placka na filtrze (np. CZYSTY, T10_GOTOWY)'))
    op.add_column('sprzet', sa.Column('filter_cake_origin_mix_id', sa.Integer(), nullable=True, comment='ID mieszaniny (TankMix), z której pochodzi obecny placek'))
    op.add_column('tank_mixes', sa.Column('process_status', sa.String(length=50), nullable=False, comment='Jawny status etapu przetwarzania mieszaniny'))
    op.add_column('tank_mixes', sa.Column('main_composition', sa.JSON(), nullable=True, comment='Słownik głównych składników z procentami, np. {"T10": 99.0}'))
    op.add_column('tank_mixes', sa.Column('wydmuch_percentage', sa.DECIMAL(precision=5, scale=2), nullable=False))
    op.add_column('tank_mixes', sa.Column('filter_remains_percentage', sa.DECIMAL(precision=5, scale=2), nullable=False))
    op.add_column('tank_mixes', sa.Column('filtration_cycles_count', sa.Integer(), nullable=False))
    op.add_column('tank_mixes', sa.Column('wydmuch_cycles_count', sa.Integer(), nullable=False))
    op.add_column('tank_mixes', sa.Column('bleaching_earth_bags_total', sa.Integer(), nullable=False))
    op.add_column('tank_mixes', sa.Column('whiteboard_id', sa.String(length=10), nullable=True, comment='Identyfikator z whiteboardu, np. (A), (B)'))
    op.add_column('tank_mixes', sa.Column('is_wydmuch_mix', sa.Boolean(), nullable=False, comment='Oznacza, czy ta mieszanina składa się wyłącznie z wydmuchów.'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tank_mixes', 'is_wydmuch_mix')
    op.drop_column('tank_mixes', 'whiteboard_id')
    op.drop_column('tank_mixes', 'bleaching_earth_bags_total')
    op.drop_column('tank_mixes', 'wydmuch_cycles_count')
    op.drop_column('tank_mixes', 'filtration_cycles_count')
    op.drop_column('tank_mixes', 'filter_remains_percentage')
    op.drop_column('tank_mixes', 'wydmuch_percentage')
    op.drop_column('tank_mixes', 'main_composition')
    op.drop_column('tank_mixes', 'process_status')
    op.drop_column('sprzet', 'filter_cake_origin_mix_id')
    op.drop_column('sprzet', 'filter_cake_status')
    op.drop_column('sprzet', 'stan_palnika')
    op.drop_column('sprzet', 'szybkosc_chlodzenia_c_na_minute')
    op.drop_column('sprzet', 'szybkosc_grzania_c_na_minute')
    # ### end Alembic commands ###
